name: Publish

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  publish:
    name: Publish
    permissions:
      contents: write # push the release tag
    environment: publish
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip publish]') && !contains(github.event.head_commit.message, '[publish skip]') }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # needed to fetch all history and tags

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          version-file: mise.toml
          version-type: strict

      - name: Publish
        run: |
          mix deps.get
          mix compile
          .github/workflows/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
