name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0 # needed to fetch all history and tags

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: 28.0.2
          elixir-version: 1.18.4

      - name: Publish
        run: |
          mix deps.get
          mix compile
          .github/workflows/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
