name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to fetch all history and tags

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 28.0.2
          elixir-version: 1.18.4

      - name: Publish
        run: |
          mix deps.get
          mix compile
          .github/workflows/publish.sh
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
